export const categories = [
  "Operação de Máquinas", 
  "Construção Civil", 
  "Gastronomia", 
  "Informática", 
  "Marketing Digital", 
  "Gestão", 
  "Agricultura", 
  "Saúde e Segurança"
];

export const cursos = [
  {
    id: 1,
    titulo: "Curso Técnico de Confeitaria na GREJUDEC",
    categoria: "Gastronomia",
    imagem: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Aulas Práticas e Dinâmicas)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Descubra o world dos doces e bolos e conquiste sua independência financeira na GREJUDEC. Aprenda uma profissão, crie, empreenda e transforme vidas com sabor!",
    objetivos: [
      "Para quem deseja aprender uma nova profissão do zero",
      "Para quem quer empreender e ter o seu próprio negócio",
      "Para quem ama confeitaria e quer se aperfeiçoar",
      "Para quem busca uma fonte de renda extra imediata"
    ],
    conteudo: [
      "Noções de Higiene e Segurança Alimentar",
      "Massas, Recheios e Coberturas",
      "Bolos Caseiros e Decorados",
      "Pães Doces e Salgados",
      "Tortas e Cheesecakes",
      "Cupcakes e Cake Pops",
      "Doces Finos e Brigadeiros Gourmet",
      "Confeitaria para Festas e Eventos",
      "Decoração com Chantilly e Pasta Americana",
      "Precificação e Gestão de Negócio"
    ],
    requisitos: "Cópia de BI; Duas fotos tipo passe; Cópia do certificado da 7ª ou 10ª classe; Ficha de inscrição (175 MT); Taxa de Inscrição: 450 MT.",
    certificacao: "Certificado Reconhecido pela GREJUDEC",
    formador: "Corpo Técnico Qualificado GREJUDEC"
  },
  {
    id: 2,
    titulo: "Curso Técnico de Confeitaria e Pastelaria (Intensivo)",
    categoria: "Gastronomia",
    imagem: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?q=80&w=1200",
    duracao: "1 Mês",
    regime: "Presencial (Aulas Práticas)",
    valor: "4.000 MT (Total)",
    precoNumerico: 4000,
    descricao: "Formação acelerada na GREJUDEC focada no mercado de trabalho e produção imediata, com opção de pagamento em duas prestações de 2.000 MT.",
    objetivos: [
      "Saia pronto(a) para o mercado de pastelaria",
      "Aprenda com professores qualificados técnicas essenciais de doçaria",
      "Preparação focada para o mercado profissional local"
    ],
    conteudo: [
      "Massas, recheios e coberturas avançadas",
      "Bolos caseiros e decorados",
      "Pães doces e salgados profissionais",
      "Tortas, cupcakes e muffins",
      "Doces finos e brigadeiros gourmet",
      "Pastelaria básica e avançada",
      "Decoração com chantilly e pasta americana",
      "Noções de higiene e segurança alimentar",
      "Precificação e gestão do seu negócio"
    ],
    requisitos: "Cópia de BI; Duas fotos tipo passe; Cópia do certificado da 7ª ou 10ª classe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado e Graduação Inclusa Reconhecidos",
    formador: "Professores Qualificados GREJUDEC"
  },
  {
    id: 3,
    titulo: "Operador de Máquinas Pesadas - Pá Mecânica",
    categoria: "Operação de Máquinas",
    imagem: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?q=80&w=1200",
    duracao: "3 Meses",
    regime: "Presencial (Aulas Teóricas e Práticas)",
    valor: "15.000 MT",
    precoNumerico: 15000,
    descricao: "Treinamento especializado focado em Operação Segura, Manutenção Básica e Prática em Campo com Pá Mecânica. Todos os formandos terão direito a uma Carta de Condução Categoria Pesada.",
    objetivos: [
      "Operação Segura de Equipamento Pesado",
      "Manutenção Básica Diária de Sistemas",
      "Prática Extensiva Eficiente em Campo"
    ],
    conteudo: [
      "Introdução às Máquinas Pesadas e Hidráulica",
      "Normas de Segurança e Prevenção de Riscos",
      "Inspeção Pré-Operacional de Rotina",
      "Técnicas de Escavação, Carga e Nivelamento",
      "Aulas Práticas Supervisionadas em Terreno Real"
    ],
    requisitos: "Inscrição: 1.200 MT. Cópia de BI; Duas fotos tipo passe; Cópia de certificado da 7ª ou 10ª classe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado Reconhecido pela GREJUDEC + Carta de Condução Pesada",
    formador: "Instrutores Qualificados GREJUDEC"
  },
  {
    id: 4,
    titulo: "Operador de Máquinas Pesadas - Retroescavadeira",
    categoria: "Operação de Máquinas",
    imagem: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?q=80&w=1200",
    duracao: "3 Meses",
    regime: "Presencial (Aulas Teóricas e Práticas)",
    valor: "16.000 MT",
    precoNumerico: 16000,
    descricao: "Capacitação técnica para operação de Retroescavadeira. Inclui direito a Carta de Condução Categoria Pesada para inserção imediata no mercado de trabalho.",
    objetivos: [
      "Operação Segura de Retroescavadeiras em Obras",
      "Domínio de Manutenção Básica do Equipamento",
      "Desenvolvimento de Prática Avançada em Campo"
    ],
    conteudo: [
      "Componentes Estruturais e Sistemas Hidráulicos",
      "Segurança Operacional e Estabilidade de Solo",
      "Checklist Prático e Manutenção Preventiva",
      "Operação com Braço de Retroescavadeira e Caçamba",
      "Prática de Escavação de Valas e Movimentação de Terra"
    ],
    requisitos: "Inscrição: 1.200 MT. Cópia de BI; Duas fotos tipo passe; Certificado escolar.",
    certificacao: "Certificado Reconhecido + Direito a Carta de Condução Categoria Pesada",
    formador: "Instrutores Qualificados GREJUDEC"
  },
  {
    id: 5,
    titulo: "Operador de Máquinas Pesadas - Empilhadeira",
    categoria: "Operação de Máquinas",
    imagem: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?q=80&w=1200",
    duracao: "3 Meses",
    regime: "Presencial (Aulas Teóricas e Práticas)",
    valor: "12.000 MT",
    precoNumerico: 12000,
    descricao: "Curso de qualificação profissional focado na movimentação logística de cargas com Empilhadeiras Industriais. Direito a Carta de Condução Pesada incluso.",
    objetivos: [
      "Operação Segura e Estabilidade de Carga",
      "Manutenção Básica e Reconhecimento de Painel",
      "Prática Eficiente em Campo e Armazéns"
    ],
    conteudo: [
      "Legislação, Conceitos e Tipos de Empilhadeiras",
      "Centro de Carga, Triângulo de Estabilidade e Capacidade",
      "Regras de Circulação e Sinalização Industrial",
      "Manuseio, Empilhamento e Transporte de Paletes",
      "Práticas Reais de Manobra e Segurança Operacional"
    ],
    requisitos: "Inscrição: 1.200 MT. Cópia de BI; Duas fotos tipo passe; Ficha de inscrição preenchida.",
    certificacao: "Certificado Profissional Reconhecido pela GREJUDEC + Carta de Condução Pesada",
    formador: "Instrutores Qualificados GREJUDEC"
  },
  {
    id: 6,
    titulo: "Operador de Máquinas Pesadas - Grua Móvel",
    categoria: "Operação de Máquinas",
    imagem: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?q=80&w=1200",
    duracao: "3 Meses",
    regime: "Presencial (Aulas Teóricas e Práticas)",
    valor: "24.000 MT",
    precoNumerico: 24000,
    descricao: "Curso técnico avançado focado no içamento, movimentação e elevação de cargas de grande porte com Grua Móvel. Qualidade que constrói o futuro.",
    objetivos: [
      "Operação Segura de Içamento e Elevação",
      "Manutenção Básica e Verificação de Cabos/Lingas",
      "Prática em Campo com Equipamento de Grande Porte"
    ],
    conteudo: [
      "Física Aplicada ao Içamento e Gráficos de Carga",
      "Sistemas de Segurança, Freios e Limites da Grua",
      "Sinalização Padrão para Movimentação de Cargas",
      "Planeamento de Operações de Alto Risco (Rigging)",
      "Prática Operacional Intensiva Supervisionada em Campo"
    ],
    requisitos: "Inscrição: 1.200 MT. Todos os estudantes que concluírem terão direito à Carta de Condução Categoria Pesada.",
    certificacao: "Certificado Reconhecido de Especialista em Gruas + Carta Pesada",
    formador: "Instrutores Qualificados GREJUDEC"
  },
  {
    id: 7,
    titulo: "Curso Técnico de Gestão Portuária",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial / Híbrido",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Formação estratégica voltada para a gestão e administração de operações logísticas, trâmites aduaneiros e contentores em terminais portuários.",
    objetivos: ["Entender a logística portuária e fluxos de mercadorias", "Dominar trâmites aduaneiros básicos", "Gestão de equipas de pátio"],
    conteudo: ["Introdução ao Ambiente Portuário", "Operações de Terminais de Contentores", "Segurança e Eficiência Logística", "Legislação Aduaneira Marítima"],
    requisitos: "Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT); Inscrição Geral de 450 MT.",
    certificacao: "Certificado de Qualificação Profissional GREJUDEC",
    formador: "Corpo Docente GREJUDEC"
  },
  {
    id: 8,
    titulo: "Curso Técnico de Informática",
    categoria: "Informática",
    imagem: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Aulas Práticas)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Capacitação completa em ferramentas digitais essenciais, hardware, redes de computadores e sistemas corporativos exigidos no mercado.",
    objetivos: ["Domínio do Pacote Office e Sistemas Operacionais", "Efetuar Manutenção Preventiva e Corretiva", "Configuração básica de Redes Locais"],
    conteudo: ["Introdução ao Windows e Ferramentas de Produtividade", "Arquitetura e Manutenção de Hardware", "Redes de Computadores e Internet Segura"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado Técnico Reconhecido pela GREJUDEC",
    formador: "Técnicos de Informática GREJUDEC"
  },
  {
    id: 9,
    titulo: "Curso Técnico de Electricidade Instaladora",
    categoria: "Construção Civil",
    imagem: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Aulas Práticas de Oficina)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Aprenda a projetar, instalar e reparar redes elétricas residenciais e comerciais de forma totalmente prática e segura de acordo com as normas técnicas.",
    objetivos: ["Interpretar esquemas e plantas elétricas residenciais", "Executar montagens e instalações de circuitos elétricos", "Aplicar normas de segurança e proteção elétrica"],
    conteudo: ["Fundamentos da Eletricidade e Grandezas Físicas", "Leitura e Desenho de Plantas Elétricas", "Instalação de Tomadas, Interruptores e Quadros de Distribuição", "Testes de Carga e Manutenção Elétrica"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Cópia do certificado escolar.",
    certificacao: "Certificado Técnico Profissional Especializado em Eletricidade",
    formador: "Engenheiros Eletricistas GREJUDEC"
  },
  {
    id: 10,
    titulo: "Curso Técnico de Empreendedorismo",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial / Híbrido",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Desenvolva uma mentalidade empreendedora forte. Aprenda a estruturar o seu próprio modelo de negócio de sucesso e gerir pequenas e médias empresas.",
    objetivos: ["Identificar oportunidades de negócio lucrativas", "Elaborar planos de negócio sólidos e funcionais", "Dominar técnicas básicas de marketing e vendas"],
    conteudo: ["Mindset Empreendedor e Inovação", "Estruturação de Plano de Negócios e Canvas", "Noções de Finanças e Fluxo de Caixa", "Gestão Estratégica e Liderança de Equipas"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado de Formação de Negócios GREJUDEC",
    formador: "Especialistas em Gestão e Negócios GREJUDEC"
  },
  {
    id: 11,
    titulo: "Curso Técnico de HST (Higiene e Segurança no Trabalho)",
    categoria: "Saúde e Segurança",
    imagem: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Formação voltada para a prevenção de acidentes, avaliação de riscos ambientais e implementação de planos de segurança em ambientes de alto risco.",
    objetivos: ["Identificar riscos biológicos, físicos e químicos em obras e indústrias", "Garantir o cumprimento da legislação de trabalho", "Implementar mapas de riscos e planos de emergência"],
    conteudo: ["Introdução às Normas Internacionais e Locais de HST", "Equipamentos de Proteção Individual e Coletiva (EPI/EPC)", "Prevenção de Incêndios e Primeiros Socorros Laborais", "Auditoria e Relatórios de Incidentes"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado Profissional de Técnico de HST",
    formador: "Auditores de Segurança Certificados GREJUDEC"
  },
  {
    id: 12,
    titulo: "Gestão de Recursos Humanos",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Capacitação com foco nos processos de recrutamento, seleção, avaliação de desempenho e administração de contratos laborais de pessoal.",
    objetivos: ["Gerir processos administrativos de contratação de trabalhadores", "Desenvolver programas de treino e retenção de talento", "Dominar trâmites de processamento de salários"],
    conteudo: ["Legislação Laboral Moçambicana", "Recrutamento, Seleção e Integração", "Avaliação de Desempenho e Clima Organizacional", "Processamento de Salários e IRPS"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Certificado escolar.",
    certificacao: "Certificado em Gestão de Recursos Humanos GREJUDEC",
    formador: "Gestores de RH do Corpo Docente GREJUDEC"
  },
  {
    id: 13,
    titulo: "Gestão de Empresas",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Visão global de administração de negócios, cobrindo planeamento estratégico, finanças organizacionais, controlo de stock e contabilidade básica.",
    objetivos: ["Coordenar e planear as atividades de uma organização", "Analisar resultados financeiros e custos operacionais", "Otimizar processos produtivos e comerciais"],
    conteudo: ["Princípios da Administração e Organização", "Contabilidade Geral e Custos", "Planeamento Estratégico e Orçamental", "Gestão de Operações e Logística de Stock"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Ficha de inscrição preenchida.",
    certificacao: "Certificado Profissional em Administração de Empresas",
    formador: "Administradores do Corpo Docente GREJUDEC"
  },
  {
    id: 14,
    titulo: "Gestão Aduaneira",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Formação técnica focada nos processos de importação, exportação, cálculo de direitos aduaneiros e trâmites de mercadorias em fronteiras e portos.",
    objetivos: ["Compreender a pauta aduaneira e regimes de mercadorias", "Preencher documentação aduaneira regulamentar", "Acompanhar processos de desalfandegamento"],
    conteudo: ["Direito Aduaneiro e Legislação de Comércio Externo", "Classificação Tarifária de Mercadorias (Sistema Harmonizado)", "Liquidação de Direitos Ad Valorem e Taxas Especiais", "Procedimentos Logísticos Fronteiriços e Portuários"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Cópia do certificado da 10ª classe.",
    certificacao: "Certificado Técnico de Especialização Aduaneira",
    formador: "Especialistas Aduaneiros GREJUDEC"
  },
  {
    id: 15,
    titulo: "Gestão de Projectos",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial / Híbrido",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Aprenda a planear, executar e monitorizar projetos sociais ou corporativos com metodologias eficientes de controlo de tempo, custos e qualidade.",
    objetivos: ["Elaborar escopos, cronogramas e orçamentos detalhados de projetos", "Gerir equipas e riscos operacionais de forma dinâmica", "Avaliar o impacto e os resultados gerados após a execução"],
    conteudo: ["Ciclo de Vida de um Projeto e Iniciação", "Planeamento: Cronograma (Gantt) e Alocação de Recursos", "Gestão de Custos, Qualidade e Riscos", "Monitoria, Avaliação e Encerramento de Contratos"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado Técnico em Gestão de Projetos GREJUDEC",
    formador: "Gestores de Projeto GREJUDEC"
  },
  {
    id: 16,
    titulo: "Gestão de Marketing e Venda",
    categoria: "Marketing Digital",
    imagem: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Formação comercial focada na captação de clientes, canais de publicidade, techniques avançadas de negociação e fecho de vendas corporativas.",
    objetivos: ["Desenvolver estratégias comerciais atraentes para o mercado", "Dominar gatilhos mentais e funis de conversão de clientes", "Gerir carteiras de clientes de forma profissional"],
    conteudo: ["Comportamento do Consumidor e Pesquisa de Mercado", "Mix de Marketing e Estratégia de Preço", "Técnicas de Vendas, Prospeção e Negociação Direta", "Pós-Venda e Fidelização"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe.",
    certificacao: "Certificado Profissional de Técnico Comercial",
    formador: "Profissionais de Vendas GREJUDEC"
  },
  {
    id: 17,
    titulo: "Curso Prático de Culinária",
    categoria: "Gastronomia",
    imagem: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Aulas Práticas em Cozinha)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Desenvolva competências práticas essenciais na preparação de pratos, organização de banquetes e cortes profissionais para o setor da restauração.",
    objetivos: ["Dominar técnicas culinárias básicas e cortes industriais", "Confecionar pratos nacionais e internacionais de alto padrão", "Aplicar práticas rigorosas de segurança alimentar"],
    conteudo: ["Segurança Alimentar e Manipulação de Alimentos", "Técnicas de Preparação, Fundos, Molhos e Caldos", "Culinária Tradicional Moçambicana e Internacional", "Empratamento e Organização de Buffets"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado de Qualificação Técnica em Culinária",
    formador: "Chefes de Cozinha GREJUDEC"
  },
  {
    id: 18,
    titulo: "Técnico de Agro-Processamento",
    categoria: "Agricultura",
    imagem: "https://images.unsplash.com/photo-1592417817098-8f3d6eb18865?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Laboratório e Prática)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Aprenda a transformar e conservar matérias-primas agrícolas locais, agregando valor comercial aos produtos agrícolas e evitando o desperdício alimentar.",
    objetivos: ["Aplicar técnicas de conservação e embalamento de alimentos", "Controlar a qualidade de produtos agro-processados", "Criar pequenas linhas de produção alimentar viáveis"],
    conteudo: ["Introdução às Cadeias de Valor Agrícolas", "Métodos de Conservação (Secagem, Desidratação e Pasteurização)", "Processamento de Frutas, Hortaliças e Cereais", "Rotulagem, Embalagem e Higiene Sanitária"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição.",
    certificacao: "Certificado de Formação Técnica em Agro-Processamento",
    formador: "Técnicos de Production Agrícola GREJUDEC"
  },
  {
    id: 19,
    titulo: "Curso Técnico de Serralharia",
    categoria: "Construção Civil",
    imagem: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Oficina Prática)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Capacitação oficinal prática para corte, soldadura, conformação e fabrico de estruturas metálicas residenciais, como portões, janelas e corrimãos.",
    objetivos: ["Operar equipamentos de corte e rebarbação com segurança", "Executar uniões soldadas (Elétrodo Revestido) com precisão", "Interpretar desenhos técnicos mecânicos básicos"],
    conteudo: ["Higiene e Segurança em Oficinas Metalomecânicas", "Metrologia Básica, Riscar e Cortar Metais", "Tecnologia de Soldadura e Tipos de Elétrodos", "Montagem e Acabamento de Estruturas de Ferro e Alumínio"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe.",
    certificacao: "Certificado Técnico de Serralharia Mecânica",
    formador: "Mestres Serralheiros Qualificados GREJUDEC"
  },
  {
    id: 20,
    titulo: "Curso Técnico de Canalização",
    categoria: "Construção Civil",
    imagem: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Oficina Prática)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Domine sistemas hidráulicos. Aprenda a montar redes de distribuição de água limpa e sistemas de escoamento de águas residuais em edifícios.",
    objetivos: ["Instalar tubagens de PVC, PPR e Galvanizados", "Montar louças sanitárias, torneiras e autoclismos", "Identificar e reparar fugas e bloqueios de redes hidráulicas"],
    conteudo: ["Introdução aos Sistemas Hidráulicos Prediais", "Leitura de Plantas de Redes de Água e Saneamento", "Técnicas de Soldadura plástica (PPR) e Encaixes de Pressão", "Manutenção Preventiva e Redes de Esgoto"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Ficha de inscrição (175 MT).",
    certificacao: "Certificado Profissional de Canalizador Predial",
    formador: "Técnicos de Hidráulica GREJUDEC"
  },
  {
    id: 21,
    titulo: "Curso de Inglês Prático e Vocacional",
    categoria: "Informática",
    imagem: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial / Prático",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Desenvolva fluência na língua inglesa com foco no mercado de trabalho global, atendimento ao cliente, termos de programação e negócios internacionais.",
    objetivos: ["Alcançar comunicação clara em diálogos quotidianos", "Dominar vocabulário técnico e corporativo", "Preparação para entrevistas de emprego e escrita profissional"],
    conteudo: ["Gramática Aplicada e Conversação Dinâmica", "Leitura e Interpretação de Textos Técnicos", "Simulações de Atendimento e Negócios em Inglês"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe.",
    certificacao: "Certificado de Proficiência em Inglês Vocacional GREJUDEC",
    formador: "Professores de Línguas Qualificados GREJUDEC"
  },
  {
    id: 22,
    titulo: "Curso Técnico de Secretariado Executivo",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Capacitação profissional para administração de escritórios, gestão de agendas corporativas, atendimento ao cliente de alto padrão e redação oficial.",
    objetivos: ["Organizar fluxos administrativos e arquivos corporativos", "Dominar técnicas de atendimento ao público e protocolo", "Elaborar relatórios, atas e correspondência institucional"],
    conteudo: ["Relações Públicas e Ética Profissional", "Gestão de Arquivos e Técnicas de Secretariado", "Redação Oficial e Comunicação Empresarial"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos passe; Ficha de inscrição.",
    certificacao: "Certificado Profissional em Secretariado Executivo",
    formador: "Especialistas em Secretariado e Protocolo GREJUDEC"
  },
  {
    id: 23,
    titulo: "Curso Técnico de Corte e Costura",
    categoria: "Construção Civil",
    imagem: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial (Oficina de Moda)",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Entre no mercado da moda e modelagem. Aprenda a desenhar moldes, cortar tecidos e operar máquinas de costura industriais e domésticas do zero.",
    objetivos: ["Interpretar e desenhar moldes de roupas diversas", "Operar com segurança máquinas de costura e corte", "Executar acabamentos e alfaiataria de alta qualidade"],
    conteudo: ["Introdução ao Desenho de Moda e Fitas Métricas", "Técnicas de Corte, Alinhamento e Preparação de Tecidos", "Costura Prática Avançada e Customização"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe.",
    certificacao: "Certificado de Formação Profissional em Corte e Costura",
    formador: "Estilistas e Alfaiates do Corpo Técnico GREJUDEC"
  },
  {
    id: 24,
    titulo: "Curso Técnico de Educação Infantil",
    categoria: "Gestão",
    imagem: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Capacitação pedagógica voltada para o cuidado, assistência e desenvolvimento psicomotor de crianças em creches, infantários e centros comunitários.",
    objetivos: ["Compreender as fases de desenvolvimento e psicologia infantil", "Planear atividades lúdicas e recreativas educativas", "Aplicar noções de nutrição e primeiros socorros infantis"],
    conteudo: ["Introdução à Pedagogia Infantil e Didática Prática", "Psicologia do Desenvolvimento e Recreação Lúdica", "Higiene, Saúde e Cuidados Básicos na Primeira Infância"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe; Certificado da 10ª ou 12ª classe.",
    certificacao: "Certificado Técnico de Educador da Primeira Infância",
    formador: "Pedagogos e Especialistas em Educação GREJUDEC"
  },
  {
    id: 25,
    titulo: "Curso Prático de Jornalismo",
    categoria: "Marketing Digital",
    imagem: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200",
    duracao: "3 a 6 Meses",
    regime: "Presencial / Prático",
    valor: "1.500 MT / Mês",
    precoNumerico: 1500,
    descricao: "Aprenda as técnicas essenciais de reportagem, redação de notícias para imprensa, rádio, televisão e gestão de conteúdos para mídia digital.",
    objetivos: ["Redigir notícias de forma clara, isenta e objetiva", "Dominar técnicas de entrevista e postura em frente às câmaras", "Compreender os princípios de ética de comunicação"],
    conteudo: ["Teoria da Comunicação e Gêneros Jornalísticos", "Técnicas de Reportagem e Redação de Notícias", "Fotojornalismo, Assessoria de Imprensa e Mídias Sociais"],
    requisitos: "Inscrição Geral: 450 MT; Cópia de BI; Duas fotos tipo passe.",
    certificacao: "Certificado de Qualificação em Técnicas Jornalísticas",
    formador: "Profissionais de Comunicação e Media GREJUDEC"
  }
];